image: alpine/latest
packages:
  - go
sources:
  - https://github.com/emersion/go-mls.git
tasks:
  - build: |
      cd go-mls
      go build -race -v ./...
  - test: |
      cd go-mls
      go test -race ./...
